### ISSUE TITLE
Export variable according to the current theme

### ISSUE THREAD

**Issue by martindzejky** [tbremer/hyper-prefers-color-scheme#2]
Hi! I would like to set the color scheme in Vim based on the current color scheme of Hyper. I'm using your plugin to dynamically switch between `hyper-solarized-light/dark` themes.

Is there any way to detect the current theme in the shell? Perhaps by checking some variable? Thanks

**Comment by tbremer** [comment]
As of now this is not something the package offers. I don't believe a child process can affect the outer environment.

**Comment by tbremer** [comment]
I am on macOS and had a similar thought. I solve it using this within a launch daemon:

```bash
[[ $(defaults read -g AppleInterfaceStyle 2>/dev/null) == "Dark" ]] && echo "Dark" > $HOME/.appearance || echo "Light" > $HOME/.appearance
```

I then query the `$HOME/.appearance` file within vim to set the background/theme.
